# Generated by Django 2.2.5 on 2021-07-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210704_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='approved_comment',
        ),
    ]
